### ISSUE TITLE
Virtual-Access interfaces should be skipped

### ISSUE THREAD

**Issue by jeremyvisser** [dotwaffle/rancid-git#19]
Inside `/usr/lib/rancid/bin/rancid`, I have commented out the following parameters to `@commandtable`, because they were very noisy:

```
#{'show snmp mib ifmib ifindex'  => 'ShowIfIndex'},
#{'show interface'      => 'ShowInterface'},
```

(I also commented out the `show shun` line too due to noise, but that is beyond the scope of this report.)

In my circumstance, the routers with the noise operate as LNS'es — i.e. terminating PPPoE or L2TP sessions, with dozens of Virtual-Access interfaces appearing and/or disappearing every hour.

However, I can see why it is useful to have the output. To reach a compromise, it may be useful to test for and skip Virtual-Access interfaces, which only last for the lifetime of the PPP session.

For example, in `sub ShowInterface`, the following line appears in two places:

```
ProcessHistory("INT","keysort",$interface->{'name'},"!Interface: " . PrintInterface($interface) . "\n") if (defined $interface);
```

Perhaps it would be possible to skip Virtual-Access interfaces (please excuse me, this is literally the first line of Perl I have ever written, which may not actually work):

```
ProcessHistory("INT","keysort",$interface->{'name'},"!Interface: " . PrintInterface($interface) . "\n") if (defined $interface && !($interface->{'name'} =~ /^Virtual-Access/));
```

With something similar in `sub ShowIfIndex` to skip Virtual-Access indexes.

Thoughts?

**Comment by jnorell** [comment]
An afterthought is this could be made a config file variable, to enable/disable as needed.  Might be overkill though, I'm happy with "ignore all Virtual-Access" in our environment (isp router terminating dsl connections).
