### ISSUE TITLE
Integrate support for Palo Alto firewalls

### ISSUE THREAD

**Issue by dotwaffle** [dotwaffle/rancid-git#27]
There's currently a branch I'm working on to integrate a Palo Alto patch-set from the mailing list.

However, there's a number of annoying things, like it continually puts in version numbers for the url-filter download, which means almost every update has the number present. I'd like to skip that, unless someone feels strongly to the contrary.

**Comment by charlesrg** [comment]
Skipping the URL-Filter or masking it would be fine, are you looking to commit your patch ?

**Comment by charlesrg** [comment]
forget about this. looks like rancid now supports native GIT and I should head back to using the main branch.

**Comment by dotwaffle** [comment]
Perfect, thanks ;) Yeah, I'm looking at deprecating this fork at some point. It's basically unmaintained at the moment -- unfortunately there's no easy way of migrating data to the upstream method of implementing git, which is annoying :S

**Comment by charlesrg** [comment]
yep, I'm  working on it and found major issues with their original stuff, getting GIT to work is not as stated in their README. I'm going to stick a bit longer with your code for now as it does work.
