### ISSUE TITLE
Git commit when SSH key has password

### ISSUE THREAD

**Issue by mhite** [dotwaffle/rancid-git#34]
Hopefully I'm not blind, but is there a way for git-rancid to use an SSH key password when performing a commit to github.com?

**Comment by dotwaffle** [comment]
Ok, so after some serious thought about this, I'm going to reject this issue.

Either the ssh key should not have a passphrase or git itself should be configured with a credential cache. This isn't a rancid issue unfortunately and is more an implementation issue.

Sorry for the delay in getting around to this!
