### ISSUE TITLE
Groups as autonomous repositories

### ISSUE THREAD

**Issue by coxley** [dotwaffle/rancid-git#40]
I haven't seen any mention of it in any of the manpages I read. Is there an option to set each group as it's own separate repositiory? 

This is desired is several use cases, especially when each group might be a separate administrative domain with different hooks desired and more. When using frontend git servers as well, would enable creating hooks to push individual groups to different projects representing within. 

Would be helpful when used within an MSP.

**Comment by dotwaffle** [comment]
Integrated upstream. Once released, I'll integrate 3.1 which will solve this once and for all!
