### ISSUE TITLE
error: no proper invocation of AM_INIT_AUTOMAKE was found.

### ISSUE THREAD

**Issue by AXVill** [dotwaffle/rancid-git#43]
$ automake --add-missing
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
Makefile.am:41: error: MK_LCLSTATEDIR does not appear in AM_CONDITIONAL
/usr/share/automake-1.14/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.14/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/share/automake-1.14/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.14/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.14/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.14/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.14/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.14/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
etc/Makefile.am:56: error: CONF_INSTALL does not appear in AM_CONDITIONAL

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic

**Comment by dotwaffle** [comment]
It's fine, it is only a warning not an error :)

Just do ./configure && make

All is good!

**Comment by AXVill** [comment]
It's works. Sorry I disturbed you.

**Comment by dotwaffle** [comment]
Not a problem. Hope you manage to get something good out of it -- don't be
afraid to ask for help :)

M
