### ISSUE TITLE
Error: invalid command name "aadd"

### ISSUE THREAD

**Issue by AxisNL** [dotwaffle/rancid-git#64]
Hey, I've been running rancid for quite some years now, makes me happy!

I now want to replace my old centos6 vm with a new centos7 one, and at the same start using our central git server (company gitlab server). (The new vm is also managed by puppet, so I'll write my own puppet module). I installed rancid from the epel7 repo, now running rancid-3.2-2.el7.x86_64.

I see the following error when I run clogin:

[rancid@nmo-ran-02 rancid]$ /usr/libexec/rancid/clogin foo
Error: invalid command name "aadd"

Any idea why that could be? Am I missing some dependency? (yum whatprovides shows no aadd executables).

**Comment by dotwaffle** [comment]
Hi there,

I'm afraid the RANCID that this repo points to us 2.x not 3.x -- this is a relatively unmaintained fork!

Have a try posting to http://www.shrubbery.net/mailman/listinfo/rancid-discuss
