### ISSUE TITLE
Upstream pull request for f5rancid?

### ISSUE THREAD

**Issue by TJM** [dotwaffle/rancid-git#67]
I must be dense, but I can't seem to find "upstream" (mentioned in #23). I would like to submit a pull request for them to pull in your ./bin/f5rancid.in at a minimum. It pains me that the OS provided package of 3.1 or 3.2 do not have this file from ~3 years ago. Apparently f5 + rancid is not very popular? We have a requirement to use OS packages at this specific customer, and have an F5 running an OS from this decade that uses tmsh :)

Thanks in advance,
Tommy

**Comment by dotwaffle** [comment]
RANCID version 3 isn't compatible with the version 2 in this repo.

I'm super busy and don't have the time to devote to it unfortunately. The way the upstream (as in, the original developers) have implemented git support is substantially different from the way this has been implemented and therefore I can't see this getting fixed any time soon without additional coders coming on board.

Either way, it's very unlikely that if this repo was magically updated overnight that it would appear in a vendor repo any time soon.

Sorry, you'll have to retrofit f5rancid yourself for the time being, I no longer have any F5 equipment to test against!

**Comment by TJM** [comment]
Right, I have been looking at yours, trying to figure out the build requirements, and it looks like there is a "fairly" up to date spec file. Also, I think I like the way you implemented git(-remote) better. 

In addition they have the following: https://bugzilla.redhat.com/show_bug.cgi?id=1224143 ... which means I am currently using a "third party" package anyhow. Perhaps we will just change back to 2.x and use your repo and "roll our own" packages :-/ 

I are just setting this up initially, so any lost history at this point is not a big deal.
