### ISSUE TITLE
removal of cleartext passwords from clogin.rc file of RANCID

### ISSUE THREAD

**Issue by SumitKu** [dotwaffle/rancid-git#83]
We are trying to avoid the usage of cleartext passwords in .cloginrc file of RANCID by using CyberArk API which provide passwords ondemand . API is capable to made available passwords of accounts been used by RANCID. IS there a way to get rid of cloginrc plaintext file by replacing it with API calls?

**Comment by dotwaffle** [comment]
No, but if you don't insert a password, the ssh call will just your ssh config. If you build an ssh config that either specifies a kerberos ticket or ssh key method, it will use that. I'm sure you can integrate an API method, but that's out of the scope of rancid ;)

Good luck!
